### ISSUE TITLE
Trying to change apparel material type made ui break 

### ISSUE THREAD

**Issue by Mey-Ha-Zah** [ISOR3X/pawn-editor#103]
https://gist.github.com/HugsLibRecordKeeper/9208f8e4391ac5e2235b35163541c8e6

Troubleshooted this on the discord, they told me to report it here.

**Comment by ISOR3X** [comment]
Known issue, we're still actively investigating what is causing it. Any reproduction steps would help.

**Comment by ISOR3X** [comment]
Fixed in the latest release!
