### ISSUE TITLE
Color hex selector is no longer present, and the color selection screen appears behind materials screen when opened

### ISSUE THREAD

**Issue by beverage** [ISOR3X/pawn-editor#105]
There are no errors or warnings in the logs, on both game load and save load.  This worked prior to the 1.0.5 release.  It seems as if regaining the ability to select materials cost the ability to select colors by hex, but I cannot see anything in the diff that looks like it obviously did that.

I tested this on a variety of objects and all had the same result.

See attached screenshots:

![Screenshot 2024-04-23 at 13 52 06](https://github.com/ISOR3X/pawn-editor/assets/2602047/f9587eca-0903-4e8e-90be-677a5006bce6)
![Screenshot 2024-04-23 at 13 52 19](https://github.com/ISOR3X/pawn-editor/assets/2602047/bf7e2df6-ca28-4bd8-8b6b-2a1190ad65c2)

**Comment by beverage** [comment]
I think I found the cause of the color window not being on top: https://github.com/ISOR3X/pawn-editor/commit/6b6abeefd360fd047b0fae03395ace22413b26e3

**Comment by beverage** [comment]
And the hex selector problems looks to be here: https://github.com/ISOR3X/pawn-editor/commit/ca202de165a8b9f82203d55d3e68413f96f5f91b

**Comment by ISOR3X** [comment]
Thanks for the report and even investigating the cause!
I agree with the edit window being a big too aggressive, I will investigate it when I have time.
As for the HEX selector, we had issues with the field validation so we switched to a button. You can still paste hex values from your clipboard, just not input them with a text field.
