### ISSUE TITLE
Pawn editor's main dialog appears behind the starting screen after clicking 'Pawn Editor' button

### ISSUE THREAD

**Issue by RC-3222** [ISOR3X/pawn-editor#107]
After clicking a button "pawn editor" button while in starting screen the pawn editor dialog appears behind the main starting screen, therefore is actually invisible/unusable.

Below are 2 screenshots: before and after clicking the button. (and if you look at the "after" one, you may notice that a slight shadow around had become a bit more noticable, which confirms that the dialog actually opened, but was drawn behind the main starting dialog (and it also disappears with a 'close' sound If you click outside, which also makes sense with `closeOnClickedOutside = true;`))
![before](https://github.com/ISOR3X/pawn-editor/assets/99599598/ea612247-2c40-4fec-b388-d9d84350bb71)
![after](https://github.com/ISOR3X/pawn-editor/assets/99599598/5e786d8a-fe35-49ca-a4f0-224460dfbdf9)

And, after looking at the most recent [commit](https://github.com/ISOR3X/pawn-editor/commit/b6088a7d372fd254caa37a23eac5813ad731f351), it seems that you changed Pawn editor's main dialog's layer to `WindowLayer.GameUI` (which, probably, has lower priority than starting screen's one). After setting it (back) to `WindowLayer.Dialog` (which is the default for the `Window` class), recompiling and testing a few tabs/dialogs (including the color picker and 'edit item' dialog), everything seems to appear as expected, so the fix, probably, could be to change the layer back to `WindowLayer.Dialog` (or even remove the explicit assignment, since it's the default anyway)

Log: https://gist.github.com/HugsLibRecordKeeper/bd17e8ee7ffc45bfe11e35716e2fece4

**Comment by ISOR3X** [comment]
Just pushed the fix to live.
