### ISSUE TITLE
Add apparel stopped working

### ISSUE THREAD

**Issue by OgamLab** [ISOR3X/pawn-editor#88]
Add apparel botton stopped doing anythig without any error in log 
![image](https://github.com/ISOR3X/pawn-editor/assets/85077536/b2785b57-5928-4c92-9989-b74d18dff95d)

**Comment by OgamLab** [comment]
Got error 
![image](https://github.com/ISOR3X/pawn-editor/assets/85077536/9dbb8b70-1a41-46d5-a3c1-ff59cc7491db)

**Comment by ISOR3X** [comment]
Bit difficult to do anything about this if we have no steps on how to reproduce this. Do you hear the sound of it opening/closing? How did you close it the last time?
