### ISSUE TITLE
Mod prevents faction naming oppertunity

### ISSUE THREAD

**Issue by Feimni** [ISOR3X/pawn-editor#94]
In the non-modded game the player gets the oppertunity to name its faction and settlement after a few in-game days. With this mod, the option to name the faction does not show op. The player only gets the option to name the settlement. If the faction was not renamed at the beginning of the game, then it will be called "New Arrivals" the whole playthrough.

**Comment by Feimni** [comment]
Note, settlement name can be fixed in development mode.

1) Activate development mode
Menu -> Options -> General -> Development mode

2) Trigger naming event
Debug actions menu -> Show more actions -> Name faction and faction base

**Comment by ISOR3X** [comment]
Once the linked PR gets merged it should be fixed in the next update. Thank you for the report.
